name: Build and Release IPA

on:
  push:
    tags:
      - 'v*'  # trigger solo su tag come v1.0.0

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'  # cambia se usi altra versione

    - name: Build IPA
      run: |
        xcodebuild -project "Pina Colada.xcodeproj" \
                   -scheme "Pina Colada" \
                   -configuration Release \
                   -sdk iphoneos \
                   -archivePath $PWD/build/PinaColada.xcarchive archive

        xcodebuild -exportArchive \
                   -archivePath $PWD/build/PinaColada.xcarchive \
                   -exportOptionsPlist ExportOptions.plist \
                   -exportPath $PWD/build

    - name: Upload IPA to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/PinaColada.ipa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
