name: Build iOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_16.0.app" || sudo xcode-select -s /Applications/Xcode.app

      - name: Build with Xcode
        run: |
          xcodebuild -project "Pina Colada.xcodeproj" \
            -scheme "Pina Colada" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            clean build

      - name: Archive app (optional)
        run: |
          xcodebuild -project "Pina Colada.xcodeproj" \
            -scheme "Pina Colada" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -configuration Release \
            clean archive -archivePath ${{ github.workspace }}/build/PinaColada.xcarchive

      - name: Run tests (optional)
        run: |
          xcodebuild test -project "Pina Colada.xcodeproj" \
            -scheme "Pina Colada" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'
