name: Build without Signing
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'  # o la versione che usi

      - name: Build archive (no signing)
        run: |
          xcodebuild -project "Pina Colada.xcodeproj" \
            -scheme "Pina Colada" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/PinaColada.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO archive

      - name: Upload xcarchive to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/PinaColada.xcarchive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
